# Site settings
email: hi@jonas.tech
hello: >
  Hi, I'm Jonas
more:
  A Berlin-based freelance mobile developer.

  I'm an advocate for user-focussed product design,
  clean code and deliberate software architectures.
  <a href="https://represent.io/jonas">Here</a> you can find my CV.
description: >
  I'm a freelance Android Developer based in Berlin who advocates for user focussed product design,
  clean code and deliberate software architectures. I like working in agile teams and strive for buidling products that users love.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonas.tech" # the base hostname & protocol for your site
twitter_username: jonasluthke
github_username:  joluet

# Build settings
markdown: kramdown

# custom collection for projects
collections:
  projects:
    output: true

exclude: [
  "/node_modules",
  "gulpfile.js",
  "package.json",
  "README.md",
  "Gemfile",
  "Gemfile.lock"
]
